import type { Order } from "../types/orderList";

export const data: Order[] = [
  {
    id: 1,
    name: "Ali",
    address: "gfggfhfjj",
    date: new Date("March 12, 2024"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 2,
    name: "Sara",
    address: "gfggfhfjj",
    date: new Date("April 5, 2024"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 3,
    name: "Reza",
    address: "gfggfhfjj",
    date: new Date("May 18, 2024"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 4,
    name: "Mina",
    address: "gfggfhfjj",
    date: new Date("June 2, 2020"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 5,
    name: "John",
    address: "gfggfhfjj",
    date: new Date("April 10, 2025"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 6,
    name: "Nina",
    address: "gfggfhfjj",
    date: new Date("April 25, 2024"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 7,
    name: "John",
    address: "gfggfhfjj",
    date: new Date("September 15, 2024"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 8,
    name: "sara",
    address: "gfggfhfjj",
    date: new Date("March 12, 2003"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 9,
    name: "ali",
    address: "gfggfhfjj",
    date: new Date("April 5, 2024"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 10,
    name: "Reza",
    address: "gfggfhfjj",
    date: new Date("May 18, 2013"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 11,
    name: "Mina",
    address: "gfggfhfjj",
    date: new Date("June 2, 2020"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 12,
    name: "John",
    address: "gfggfhfjj",
    date: new Date("April 11, 2024"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 13,
    name: "mina",
    address: "gfggfhfjj",
    date: new Date("April 25, 2024"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 14,
    name: "John",
    address: "gfggfhfjj",
    date: new Date("September 15, 2024"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 15,
    name: "jana",
    address: "gfggfhfjj",
    date: new Date("March 12, 2024"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 16,
    name: "Sara",
    address: "gfggfhfjj",
    date: new Date("April 5, 2022"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 17,
    name: "Reza",
    address: "gfggfhfjj",
    date: new Date("May 17, 2024"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 18,
    name: "maryam",
    address: "gfggfhfjj",
    date: new Date("June 2, 2025"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 19,
    name: "ali",
    address: "gfggfhfjj",
    date: new Date("April 10, 2025"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 20,
    name: "Nina",
    address: "gfggfhfjj",
    date: new Date("April 25, 2024"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
  {
    id: 21,
    name: "afshin",
    address: "gfggfhfjj",
    date: new Date("September 15, 2024"),
    type: ["Book & Stationary"],
    status: ["Completed"],
  },
];
export const ORDER_TYPES = [
  "Health & Medicine",
  "Book & Stationary",
  "Services & Industry",
  "Fashion & Beauty",
  "Home & Living",
  "Electronics",
  "Mobile & Phone",
  "Accessories",
] as const;
export const itemsPerPage: number = 7;
