import type { Order } from "../types/orderList";


export const ORDER_TYPES = [
  "Health & Medicine",
  "Book & Stationary",
  "Services & Industry",
  "Fashion & Beauty",
  "Home & Living",
  "Electronics",
  "Mobile & Phone",
  "Accessories",
] as const;

export const ORDER_STATUSES = [
  "Completed",
  "Processing",
  "Rejected",
  "On Hold",
  "In Transit",
] as const;

export const data: Order[] = [
  {
    id: 1,
    name: "Ali",
    address: "Tehran, Valiasr",
    date: new Date("March 12, 2024"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 2,
    name: "Sara",
    address: "Isfahan, Sepahan",
    date: new Date("April 5, 2024"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 3,
    name: "Reza",
    address: "Shiraz, Zand",
    date: new Date("May 18, 2024"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 4,
    name: "Mina",
    address: "Tabriz, El Goli",
    date: new Date("June 2, 2020"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 5,
    name: "John",
    address: "London, Oxford",
    date: new Date("April 10, 2025"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 6,
    name: "Nina",
    address: "Berlin, Mitte",
    date: new Date("April 25, 2024"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 7,
    name: "Omid",
    address: "Tehran, Vanak",
    date: new Date("September 15, 2024"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 8,
    name: "Sara",
    address: "Dubai, Marina",
    date: new Date("March 12, 2003"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 9,
    name: "Ali",
    address: "Mashhad, Ahmadabad",
    date: new Date("April 5, 2024"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 10,
    name: "Reza",
    address: "Yazd, Safaieh",
    date: new Date("May 18, 2013"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 11,
    name: "Mina",
    address: "Kerman, Shahrdari",
    date: new Date("June 2, 2020"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 12,
    name: "John",
    address: "New York, Brooklyn",
    date: new Date("April 11, 2024"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 13,
    name: "Sara",
    address: "Paris, Louvre",
    date: new Date("April 25, 2024"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 14,
    name: "Ali",
    address: "Rome, Centro",
    date: new Date("September 15, 2024"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 15,
    name: "Nina",
    address: "Istanbul, Taksim",
    date: new Date("March 12, 2024"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 16,
    name: "Reza",
    address: "Shiraz, Azadi",
    date: new Date("April 5, 2022"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 17,
    name: "Mina",
    address: "Tehran, Saadat Abad",
    date: new Date("May 17, 2024"),
     type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 18,
    name: "John",
    address: "London, Soho",
    date: new Date("June 2, 2025"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 19,
    name: "Ali",
    address: "Tabriz, El Goli",
    date: new Date("April 10, 2025"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 20,
    name: "Sara",
    address: "Berlin, Kreuzberg",
    date: new Date("April 25, 2024"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 21,
    name: "Omid",
    address: "Tehran, Jordan",
    date: new Date("September 15, 2024"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 22,
    name: "Nina",
    address: "Dubai, Downtown",
    date: new Date("March 12, 2024"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 23,
    name: "Reza",
    address: "Mashhad, Ghaem",
    date: new Date("May 18, 2024"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 24,
    name: "Mina",
    address: "Yazd, Amir Chakhmaq",
    date: new Date("June 2, 2020"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 25,
    name: "John",
    address: "New York, Manhattan",
    date: new Date("April 11, 2024"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 26,
    name: "Sara",
    address: "Paris, Eiffel",
    date: new Date("April 25, 2024"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 27,
    name: "Ali",
    address: "Rome, Trastevere",
    date: new Date("September 15, 2024"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
  {
    id: 28,
    name: "Nina",
    address: "Istanbul, Besiktas",
    date: new Date("March 12, 2003"),
    type: [ORDER_TYPES[Math.floor(Math.random() * ORDER_TYPES.length)]],
    status: [ORDER_STATUSES[Math.floor(Math.random() * ORDER_STATUSES.length)]],
  },
];

export const itemsPerPage: number = 7;